spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: lb://CUSTOMERSERVICE
          predicates:
            Path= /api/customers/**
        - id: r2
          uri: lb://INVENTORYSERVICE
          predicates:
            Path= /api/products/**

